In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [5]:
df = pd.read_csv("../datasets/kobe.csv")
data = df.dropna() # Suppression des lignes(les tirs) dont nous ne connaissons pas l'issue(marqué ou manqué)
qualitative_vars = ["action_type", "combined_shot_type", "game_event_id", "game_id", 
                    "period", "playoffs", "season", "shot_type",
                    "shot_zone_area", "shot_zone_basic", "shot_zone_range", "team_name", "game_date", "matchup", "opponent"]
quantitative_vars = [col for col in df.columns if col not in qualitative_vars + ["shot_made_flag", "shot_id", 'team_id']]  # garder le shot_id ? 
target = data["shot_made_flag"].values

In [6]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
values = data["opponent"]
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded).astype(int)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

1        POR
2        POR
3        POR
4        POR
5        POR
        ... 
30691    IND
30692    IND
30694    IND
30695    IND
30696    IND
Name: opponent, Length: 25697, dtype: object
[25 25 25 ... 11 11 11]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['POR']


c:\Users\guilh\anaconda3\envs\envguilhem\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [7]:
target = target.reshape(25697,1)

In [8]:
coor = np.concatenate((onehot_encoded, target), axis=1)

In [9]:
coor[:,-1]

array([0., 1., 0., ..., 1., 0., 0.])

In [10]:
# Calculer la matrice de corrélation
correlation_matrix = np.corrcoef(coor)

# Obtenir la corrélation de 'shot_made_flag' avec toutes les autres variables
target_correlation = correlation_matrix[:,-1]

In [11]:
print(target_correlation)

[-0.03030303 -0.04351941 -0.03030303 ...  0.69631062  1.
  1.        ]


In [13]:
target_correlation.shape

(25697,)

In [12]:
for i in target_correlation:
    print(i)

-0.030303030303030314
-0.04351941398892446
-0.030303030303030314
-0.04351941398892446
-0.030303030303030314
-0.04351941398892446
-0.04351941398892446
-0.030303030303030314
-0.030303030303030314
-0.04351941398892447
-0.04351941398892447
-0.030303030303030314
-0.030303030303030314
-0.030303030303030314
-0.04351941398892447
-0.030303030303030314
-0.030303030303030314
-0.030303030303030314
-0.04351941398892447
-0.04351941398892447
-0.04351941398892447
-0.030303030303030314
-0.030303030303030314
-0.030303030303030314
-0.030303030303030314
-0.030303030303030314
-0.04351941398892447
-0.030303030303030314
-0.04351941398892447
-0.04351941398892447
-0.030303030303030314
-0.04351941398892447
-0.04351941398892447
-0.030303030303030314
-0.04351941398892447
-0.030303030303030314
-0.04351941398892447
-0.04351941398892447
-0.030303030303030314
-0.030303030303030314
-0.030303030303030325
-0.030303030303030325
-0.030303030303030325
-0.04351941398892446
-0.04351941398892446
-0.04351941398892446
-0.030303